export const printerFallbackProject = {
  projectName: "CoreXY 3D Printer",
  summary:
    "A desktop CoreXY-style 3D printer with an aluminum extrusion frame, heated bed, gantry, print head, motion hardware, and electronics.",
  statusLabel: "Fallback manifest",
  statusMetric: "3 motion axes",
  placeholders: [
    {
      title: "LLM hardware manifest",
      status: "Real when API key is configured",
      detail:
        "The backend asks the configured LLM provider for a structured manifest: project summary, BOM rows, catalog-name aliases, and simple 3D primitives.",
    },
    {
      title: "3D geometry",
      status: "Proxy CAD now",
      detail:
        "The viewer renders boxes, cylinders, and spheres from the manifest. Replace primitive arrays with Cadybara STEP/STL URLs when the CAD service is connected.",
    },
    {
      title: "Supplier search",
      status: "Generated links now",
      detail:
        "Supplier cards use catalog-name suggestions to build searches. A later version can call Octopart, Digi-Key, or distributor APIs for live pricing and stock.",
    },
    {
      title: "Pricing",
      status: "Placeholder",
      detail:
        "The schema has room for cost fields, but this demo intentionally avoids fake prices until a supplier API is wired in.",
    },
  ],
  parts: [
    {
      id: "extrusion-frame",
      name: "2020 aluminum extrusion frame",
      type: "cots",
      qty: 1,
      material: "anodized aluminum",
      partNo: "2020 T-slot extrusion kit",
      description: "Rigid cube frame supporting the motion system and enclosure panels.",
      catalogNameSuggestions: ["2020 aluminum extrusion kit", "T-slot extrusion 2020", "V-slot 2020 frame kit"],
      manufacturers: ["MISUMI", "OpenBuilds", "80/20", "McMaster-Carr catalog"],
      specsToConfirm: ["cut lengths", "slot profile", "corner hardware", "squareness tolerance"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.16, 2.4, 0.16], position: [-1.7, 1.2, -1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 2.4, 0.16], position: [1.7, 1.2, -1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 2.4, 0.16], position: [-1.7, 1.2, 1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 2.4, 0.16], position: [1.7, 1.2, 1.25], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "top-frame-rails",
      name: "Top frame rail set",
      type: "cots",
      qty: 1,
      material: "anodized aluminum",
      partNo: "2020 extrusion cross rails",
      description: "Upper rectangular frame that carries the CoreXY idlers and gantry rails.",
      catalogNameSuggestions: ["2020 extrusion cross rail", "CoreXY printer frame rail", "T-slot cross member"],
      manufacturers: ["MISUMI", "OpenBuilds", "80/20", "McMaster-Carr catalog"],
      specsToConfirm: ["rail lengths", "corner brackets", "belt clearance", "hole tapping"],
      geometry: {
        primitives: [
          { shape: "box", size: [3.56, 0.16, 0.16], position: [0, 2.4, -1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [3.56, 0.16, 0.16], position: [0, 2.4, 1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 0.16, 2.66], position: [-1.7, 2.4, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 0.16, 2.66], position: [1.7, 2.4, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "bottom-frame-rails",
      name: "Bottom frame rail set",
      type: "cots",
      qty: 1,
      material: "anodized aluminum",
      partNo: "2020 extrusion base rails",
      description: "Lower rectangular frame that supports the bed lift and electronics bay.",
      catalogNameSuggestions: ["2020 extrusion base rail", "3D printer frame kit", "T-slot printer base"],
      manufacturers: ["MISUMI", "OpenBuilds", "80/20", "McMaster-Carr catalog"],
      specsToConfirm: ["rail lengths", "corner brackets", "rubber feet", "electronics clearance"],
      geometry: {
        primitives: [
          { shape: "box", size: [3.56, 0.16, 0.16], position: [0, 0.08, -1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [3.56, 0.16, 0.16], position: [0, 0.08, 1.25], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 0.16, 2.66], position: [-1.7, 0.08, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.16, 0.16, 2.66], position: [1.7, 0.08, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "heated-bed",
      name: "Heated build plate assembly",
      type: "cots",
      qty: 1,
      material: "aluminum tooling plate",
      partNo: "310 mm heated bed",
      description: "Flat heated bed with magnetic build surface and underside insulation.",
      catalogNameSuggestions: ["310mm heated bed", "magnetic PEI build plate", "aluminum 3D printer bed"],
      manufacturers: ["LDO Motors", "Mandala Rose Works", "Prusa Research", "Biqu"],
      specsToConfirm: ["bed voltage", "thermistor type", "flatness", "mount hole pattern"],
      geometry: {
        primitives: [
          { shape: "box", size: [2.45, 0.08, 1.85], position: [0, 0.72, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [2.35, 0.04, 1.75], position: [0, 0.79, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "bed-lift",
      name: "Z bed lift hardware",
      type: "cots",
      qty: 1,
      material: "steel lead screws and linear guides",
      partNo: "T8 lead screw lift kit",
      description: "Three-point Z lift system that raises and lowers the heated bed.",
      catalogNameSuggestions: ["T8 lead screw 3D printer kit", "Z axis linear rail", "3D printer bed lift"],
      manufacturers: ["LDO Motors", "Misumi", "THK", "RobotDigg"],
      specsToConfirm: ["lead screw pitch", "guide length", "motor coupling", "bed mount pattern"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.045, 0.045, 1.45], position: [-1.18, 0.75, -0.82], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 1.45], position: [1.18, 0.75, -0.82], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 1.45], position: [0, 0.75, 0.92], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [2.6, 0.12, 0.18], position: [0, 0.58, -0.82], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "x-gantry",
      name: "X gantry linear rail",
      type: "cots",
      qty: 1,
      material: "steel rail on aluminum beam",
      partNo: "MGN12H rail + 2020 beam",
      description: "Cross gantry that carries the print head across the build area.",
      catalogNameSuggestions: ["MGN12H linear rail", "CoreXY X gantry rail", "3D printer linear guide"],
      manufacturers: ["HIWIN", "LDO Motors", "CNA linear rail", "RobotDigg"],
      specsToConfirm: ["rail length", "carriage preload", "straightness", "mount pitch"],
      geometry: {
        primitives: [
          { shape: "box", size: [2.75, 0.14, 0.14], position: [0, 1.86, 0.52], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [2.55, 0.06, 0.08], position: [0, 1.96, 0.52], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "y-rails",
      name: "Y axis rail pair",
      type: "cots",
      qty: 2,
      material: "steel linear rails",
      partNo: "MGN12H side rails",
      description: "Parallel rails that move the X gantry front to back.",
      catalogNameSuggestions: ["MGN12H 350mm linear rail", "CoreXY Y rail pair", "linear guide rail pair"],
      manufacturers: ["HIWIN", "LDO Motors", "CNA linear rail", "RobotDigg"],
      specsToConfirm: ["matched rail length", "carriage count", "preload", "mounting hardware"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.1, 0.08, 2.15], position: [-1.36, 1.92, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.1, 0.08, 2.15], position: [1.36, 1.92, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.26, 0.16, 0.26], position: [-1.36, 1.88, 0.52], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.26, 0.16, 0.26], position: [1.36, 1.88, 0.52], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "print-head",
      name: "Direct-drive print head",
      type: "cots",
      qty: 1,
      material: "hotend and extruder assembly",
      partNo: "Revo / Rapido direct drive toolhead",
      description: "Compact toolhead with extruder, hotend, part cooling, and nozzle.",
      catalogNameSuggestions: ["direct drive extruder hotend", "3D printer toolhead", "Rapido hotend extruder", "Revo hotend extruder"],
      manufacturers: ["E3D", "Phaetus", "Bondtech", "LDO Motors"],
      specsToConfirm: ["filament diameter", "voltage", "nozzle ecosystem", "fan voltage"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.38, 0.44, 0.32], position: [0.42, 1.62, 0.52], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.12, 0.1, 0.32], position: [0.42, 1.3, 0.52], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.02, 0.14], position: [0.42, 1.07, 0.52], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "corexy-belts",
      name: "CoreXY belt path",
      type: "cots",
      qty: 1,
      material: "GT2 reinforced belt",
      partNo: "GT2 6 mm belt loop",
      description: "Crossed belt routing that drives the print head in X and Y.",
      catalogNameSuggestions: ["GT2 6mm timing belt", "CoreXY belt kit", "3D printer timing belt"],
      manufacturers: ["Gates", "Powge", "Bando", "LDO Motors"],
      specsToConfirm: ["belt width", "tooth pitch", "reinforcement", "closed vs open loop"],
      geometry: {
        primitives: [
          { shape: "box", size: [3.0, 0.035, 0.035], position: [0, 2.2, -0.98], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [3.0, 0.035, 0.035], position: [0, 2.16, 0.98], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.035, 0.035, 2.0], position: [-1.46, 2.18, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.035, 0.035, 2.0], position: [1.46, 2.18, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "xy-motors",
      name: "XY stepper motor pair",
      type: "cots",
      qty: 2,
      material: "stepper motor assemblies",
      partNo: "NEMA 17 high torque",
      description: "Two synchronized motors that drive the CoreXY belt path.",
      catalogNameSuggestions: ["NEMA 17 stepper motor", "CoreXY XY motor pair", "high torque 3D printer stepper"],
      manufacturers: ["LDO Motors", "Moons", "StepperOnline", "Oriental Motor"],
      specsToConfirm: ["holding torque", "shaft length", "current rating", "connector pinout"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.38, 0.38, 0.38], position: [-1.35, 2.02, -1.48], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.38, 0.38, 0.38], position: [1.35, 2.02, -1.48], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.09, 0.09, 0.18], position: [-1.35, 2.02, -1.22], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.09, 0.09, 0.18], position: [1.35, 2.02, -1.22], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "idler-set",
      name: "Idler pulley set",
      type: "cots",
      qty: 8,
      material: "aluminum pulleys with bearings",
      partNo: "GT2 20T idler pulley",
      description: "Corner pulleys routing the CoreXY belts around the frame.",
      catalogNameSuggestions: ["GT2 idler pulley 20T", "CoreXY idler pulley kit", "3D printer pulley bearing"],
      manufacturers: ["Gates", "Powge", "RobotDigg", "LDO Motors"],
      specsToConfirm: ["belt width", "bearing bore", "flanged vs smooth", "stack height"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.12, 0.12, 0.08], position: [-1.48, 2.18, -1.02], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.12, 0.12, 0.08], position: [1.48, 2.18, -1.02], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.12, 0.12, 0.08], position: [-1.48, 2.18, 1.02], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.12, 0.12, 0.08], position: [1.48, 2.18, 1.02], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "electronics-bay",
      name: "Controller electronics bay",
      type: "cots",
      qty: 1,
      material: "PCB and wiring assemblies",
      partNo: "32-bit 3D printer controller",
      description: "Main controller, stepper drivers, power distribution, and wiring tucked below the bed.",
      catalogNameSuggestions: ["32-bit 3D printer controller board", "Klipper controller board", "TMC stepper driver board"],
      manufacturers: ["BigTreeTech", "Duet3D", "Mellow", "LDO Motors"],
      specsToConfirm: ["driver count", "input voltage", "heater current", "firmware support"],
      geometry: {
        primitives: [
          { shape: "box", size: [1.05, 0.16, 0.72], position: [0.82, 0.28, 1.0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.62, 0.14, 0.42], position: [-0.88, 0.28, 1.04], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "power-supply",
      name: "24 V power supply",
      type: "cots",
      qty: 1,
      material: "enclosed switching supply",
      partNo: "24 V 350 W PSU",
      description: "Main power supply for heaters, motors, fans, and controller electronics.",
      catalogNameSuggestions: ["24V 350W power supply", "Mean Well 24V PSU", "3D printer power supply"],
      manufacturers: ["Mean Well", "TDK-Lambda", "Delta Electronics", "LRS"],
      specsToConfirm: ["voltage", "wattage", "cooling", "safety certifications"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.72, 0.32, 0.48], position: [-0.95, 0.34, -1.02], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.56, 0.04, 0.36], position: [-0.95, 0.53, -1.02], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "spool-holder",
      name: "Filament spool holder",
      type: "custom",
      qty: 1,
      material: "printed nylon or PETG",
      partNo: "",
      description: "Top-mounted spool support with a low-friction axle.",
      catalogNameSuggestions: [],
      manufacturers: ["Cadybara", "local FDM print", "Xometry network"],
      specsToConfirm: ["spool width", "axle diameter", "mount pattern", "filament path"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.42, 0.42, 0.24], position: [-0.8, 2.9, 0], rotation: [1.5708, 0, 0], colorRole: "custom" },
          { shape: "cylinder", size: [0.08, 0.08, 1.1], position: [-0.8, 2.9, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.18, 0.55, 0.14], position: [-1.34, 2.64, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "enclosure-panels",
      name: "Clear enclosure panel set",
      type: "custom",
      qty: 1,
      material: "polycarbonate sheet",
      partNo: "",
      description: "Transparent side and rear panels for thermal stability and draft protection.",
      catalogNameSuggestions: [],
      manufacturers: ["SendCutSend", "local plastics shop", "Xometry network", "McMaster-Carr catalog"],
      specsToConfirm: ["sheet thickness", "panel dimensions", "fastener holes", "door hinge layout"],
      geometry: {
        primitives: [
          { shape: "box", size: [3.25, 1.9, 0.035], position: [0, 1.24, -1.42], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.035, 1.9, 2.25], position: [-1.88, 1.24, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.035, 1.9, 2.25], position: [1.88, 1.24, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "fastener-kit",
      name: "Metric fastener and bracket kit",
      type: "cots",
      qty: 1,
      material: "alloy steel",
      partNo: "M3/M5 socket head assortment",
      description: "Frame brackets, tee nuts, screws, washers, and cable clamps for final assembly.",
      catalogNameSuggestions: [
        "M3 M5 socket head screw kit",
        "2020 extrusion corner bracket kit",
        "T-slot tee nut assortment",
        "3D printer fastener kit",
      ],
      manufacturers: ["McMaster-Carr catalog", "Bolt Depot", "MISUMI", "OpenBuilds"],
      specsToConfirm: ["thread sizes", "length mix", "tee nut profile", "bracket count"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [-1.52, 0.22, -1.08], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [1.52, 0.22, -1.08], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [-1.52, 0.22, 1.08], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [1.52, 0.22, 1.08], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
  ],
};

export const robotArmFallbackProject = {
  projectName: "6DOF Robotic Arm",
  summary:
    "A desktop-scale 6-axis robotic arm with a rotating base, shoulder, elbow, wrist, tool flange, and two-finger gripper.",
  statusLabel: "Fallback manifest",
  statusMetric: "6 driven axes",
  placeholders: printerFallbackProject.placeholders,
  parts: [
    {
      id: "base-plate",
      name: "Custom base plate",
      type: "custom",
      qty: 1,
      material: "6061 aluminum",
      partNo: "",
      description: "Circular mounting foundation with bolt pattern for the rotating base.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["plate thickness", "bolt pattern", "bearing pocket", "surface finish"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [1.35, 1.35, 0.18], position: [0, 0.06, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "cylinder", size: [0.75, 0.75, 0.18], position: [0, 0.24, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "base-actuator",
      name: "J1 geared base actuator",
      type: "cots",
      qty: 1,
      material: "motor assembly",
      partNo: "NEMA 23 + 50:1 gearbox",
      description: "Primary yaw actuator for the arm base.",
      catalogNameSuggestions: ["NEMA 23 geared stepper motor", "robot base actuator", "closed-loop stepper gearbox"],
      manufacturers: ["Oriental Motor", "StepperOnline", "Robotis Dynamixel", "goBILDA"],
      specsToConfirm: ["stall torque", "speed", "voltage", "control protocol"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.48, 0.48, 0.6], position: [0, 0.62, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "shoulder-yoke",
      name: "Custom shoulder yoke",
      type: "custom",
      qty: 1,
      material: "6061 aluminum",
      partNo: "",
      description: "Forked bracket holding shoulder bearings and the upper arm pivot.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["bearing bore", "shaft clearance", "side plate thickness", "servo mount pattern"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.22, 1.02, 0.24], position: [-0.55, 1.18, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.22, 1.02, 0.24], position: [0.55, 1.18, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.28, 0.2, 0.3], position: [0, 0.78, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "shoulder-actuator",
      name: "J2 shoulder actuator",
      type: "cots",
      qty: 1,
      material: "servo assembly",
      partNo: "High-torque servo, 60 kg-cm",
      description: "Raises and lowers the upper arm link.",
      catalogNameSuggestions: ["high torque servo motor 60 kg-cm", "robot shoulder servo", "smart servo actuator"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA"],
      specsToConfirm: ["stall torque", "horn spline", "voltage", "mounting tabs"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.42, 0.42, 0.84], position: [0, 1.34, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "upper-arm-link",
      name: "Custom upper arm link",
      type: "custom",
      qty: 1,
      material: "carbon fiber tube",
      partNo: "",
      description: "Lightweight structural member between shoulder and elbow.",
      catalogNameSuggestions: [],
      manufacturers: ["Rock West Composites", "DragonPlate", "local composites shop"],
      specsToConfirm: ["tube OD/ID", "fiber layup", "cut length", "insert bonding method"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.34, 1.95, 0.34], position: [0.46, 2.05, 0], rotation: [0, 0, -0.56], colorRole: "custom" },
        ],
      },
    },
    {
      id: "elbow-actuator",
      name: "J3 elbow actuator and hub",
      type: "cots",
      qty: 1,
      material: "servo and aluminum hub",
      partNo: "High-torque servo, 45 kg-cm",
      description: "Controls the elbow pitch axis and anchors the forearm link.",
      catalogNameSuggestions: ["high torque servo motor 45 kg-cm", "robot elbow servo", "servo actuator"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA"],
      specsToConfirm: ["stall torque", "speed", "voltage", "backlash"],
      geometry: {
        primitives: [
          { shape: "sphere", size: [0.44, 0.44, 0.44], position: [0.93, 2.83, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "cylinder", size: [0.36, 0.36, 0.72], position: [0.93, 2.83, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "forearm-link",
      name: "Custom forearm link",
      type: "custom",
      qty: 1,
      material: "carbon fiber tube",
      partNo: "",
      description: "Second arm segment carrying wrist loads.",
      catalogNameSuggestions: [],
      manufacturers: ["Rock West Composites", "DragonPlate", "local composites shop"],
      specsToConfirm: ["tube OD/ID", "cut length", "end interface", "twist stiffness"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.28, 1.62, 0.28], position: [1.55, 2.34, 0], rotation: [0, 0, -2.24], colorRole: "custom" },
        ],
      },
    },
    {
      id: "wrist-housing",
      name: "Custom wrist housing",
      type: "custom",
      qty: 1,
      material: "nylon SLS",
      partNo: "",
      description: "Compact housing for the wrist roll, pitch, and yaw servos.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local SLS bureau"],
      specsToConfirm: ["wall thickness", "servo clearance", "bearing seats", "wire routing"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.62, 0.48, 0.54], position: [2.2, 1.86, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "cylinder", size: [0.2, 0.2, 0.58], position: [2.22, 1.86, 0], rotation: [0, 0, 1.5708], colorRole: "cots" },
          { shape: "box", size: [0.46, 0.2, 0.22], position: [2.56, 1.86, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "tool-flange",
      name: "Custom tool flange",
      type: "custom",
      qty: 1,
      material: "6061 aluminum",
      partNo: "",
      description: "Universal wrist output plate for end effectors.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["bolt circle", "pilot diameter", "tool pattern", "thickness"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.28, 0.28, 0.12], position: [2.78, 1.86, 0], rotation: [0, 0, 1.5708], colorRole: "custom" },
        ],
      },
    },
    {
      id: "gripper-kit",
      name: "Two-finger gripper kit",
      type: "cots",
      qty: 1,
      material: "gripper assembly",
      partNo: "Parallel gripper, 20 mm stroke",
      description: "Demo end effector for picking small objects.",
      catalogNameSuggestions: ["parallel robot gripper", "two finger gripper", "servo gripper kit"],
      manufacturers: ["RobotShop", "ServoCity", "Robotiq", "OnRobot"],
      specsToConfirm: ["stroke", "payload", "mount pattern", "servo or pneumatic"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.28, 0.34, 0.62], position: [2.98, 1.86, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.72, 0.14, 0.13], position: [3.36, 1.94, 0.26], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.72, 0.14, 0.13], position: [3.36, 1.94, -0.26], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "joint-hardware",
      name: "Bearings, shafts, and fasteners",
      type: "cots",
      qty: 1,
      material: "steel hardware assortment",
      partNo: "608-2RS bearings + 8 mm shafts + M3/M4 screws",
      description: "Common joint bearings, shafts, screws, washers, and locknuts for the full assembly.",
      catalogNameSuggestions: ["608-2RS bearing", "8mm hardened shaft", "M3 M4 socket head screw kit"],
      manufacturers: ["SKF", "NSK", "MISUMI", "McMaster-Carr catalog"],
      specsToConfirm: ["bearing dimensions", "shaft length", "thread sizes", "quantity"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.08, 0.08, 1.28], position: [0, 1.34, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.06, 0.06, 0.98], position: [0.93, 2.83, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [0.98, 0.21, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [-0.98, 0.21, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
  ],
};

export const quadcopterFallbackProject = {
  projectName: "Inspection Quadcopter",
  summary:
    "A compact inspection drone with a carbon plate airframe, four brushless motors, protected propellers, battery, flight controller, and camera payload.",
  statusLabel: "Fallback manifest",
  statusMetric: "4 rotors",
  placeholders: printerFallbackProject.placeholders,
  parts: [
    {
      id: "carbon-frame",
      name: "Custom carbon fiber airframe",
      type: "custom",
      qty: 1,
      material: "carbon fiber plate",
      partNo: "",
      description: "X-frame body with central plates and four motor arms.",
      catalogNameSuggestions: [],
      manufacturers: ["SendCutSend", "DragonPlate", "Rock West Composites", "local CNC router shop"],
      specsToConfirm: ["plate thickness", "arm width", "motor bolt pattern", "battery strap slots"],
      geometry: {
        primitives: [
          { shape: "box", size: [2.8, 0.12, 0.28], position: [0, 0.78, 0], rotation: [0, 0.7854, 0], colorRole: "custom" },
          { shape: "box", size: [2.8, 0.12, 0.28], position: [0, 0.78, 0], rotation: [0, -0.7854, 0], colorRole: "custom" },
          { shape: "box", size: [0.78, 0.16, 0.62], position: [0, 0.84, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.62, 0.08, 0.5], position: [0, 1.08, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "motor-set",
      name: "Brushless motor set",
      type: "cots",
      qty: 4,
      material: "aluminum motor assemblies",
      partNo: "2207 1700KV motors",
      description: "Four outrunner motors sized for a compact inspection quadcopter.",
      catalogNameSuggestions: ["2207 brushless motor", "quadcopter motor 1700KV", "FPV drone motor set"],
      manufacturers: ["T-Motor", "Hobbywing", "iFlight", "Lumenier"],
      specsToConfirm: ["KV rating", "shaft size", "mount pattern", "prop size compatibility"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.2, 0.2, 0.18], position: [-1.1, 0.92, -1.1], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.2, 0.2, 0.18], position: [1.1, 0.92, -1.1], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.2, 0.2, 0.18], position: [-1.1, 0.92, 1.1], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.2, 0.2, 0.18], position: [1.1, 0.92, 1.1], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "propeller-set",
      name: "Propeller set",
      type: "cots",
      qty: 4,
      material: "glass-filled nylon",
      partNo: "5 inch tri-blade props",
      description: "Matched propellers mounted above each motor.",
      catalogNameSuggestions: ["5 inch drone propeller", "FPV tri-blade prop", "quadcopter propeller set"],
      manufacturers: ["Gemfan", "HQProp", "DALProp", "APC Propellers"],
      specsToConfirm: ["diameter", "pitch", "hub bore", "CW/CCW pair count"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.86, 0.035, 0.12], position: [-1.1, 1.08, -1.1], rotation: [0, 0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.12, 0.035, 0.86], position: [-1.1, 1.08, -1.1], rotation: [0, 0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.86, 0.035, 0.12], position: [1.1, 1.08, -1.1], rotation: [0, -0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.12, 0.035, 0.86], position: [1.1, 1.08, -1.1], rotation: [0, -0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.86, 0.035, 0.12], position: [-1.1, 1.08, 1.1], rotation: [0, -0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.12, 0.035, 0.86], position: [-1.1, 1.08, 1.1], rotation: [0, -0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.86, 0.035, 0.12], position: [1.1, 1.08, 1.1], rotation: [0, 0.25, 0], colorRole: "cots" },
          { shape: "box", size: [0.12, 0.035, 0.86], position: [1.1, 1.08, 1.1], rotation: [0, 0.25, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "prop-guards",
      name: "Custom propeller guard set",
      type: "custom",
      qty: 1,
      material: "printed nylon",
      partNo: "",
      description: "Lightweight guard hoops for indoor inspection and close-quarter flying.",
      catalogNameSuggestions: [],
      manufacturers: ["Cadybara", "local FDM print", "Xometry network"],
      specsToConfirm: ["prop clearance", "mount tabs", "wall thickness", "impact material"],
      geometry: {
        primitives: [
          { shape: "box", size: [1.1, 0.04, 0.05], position: [-1.1, 1.03, -1.65], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [-1.1, 1.03, -0.55], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [-1.65, 1.03, -1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [-0.55, 1.03, -1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [1.1, 1.03, -1.65], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [1.1, 1.03, -0.55], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [0.55, 1.03, -1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [1.65, 1.03, -1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [-1.1, 1.03, 0.55], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [-1.1, 1.03, 1.65], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [-1.65, 1.03, 1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [-0.55, 1.03, 1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [1.1, 1.03, 0.55], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.1, 0.04, 0.05], position: [1.1, 1.03, 1.65], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [0.55, 1.03, 1.1], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.05, 0.04, 1.1], position: [1.65, 1.03, 1.1], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "battery-pack",
      name: "LiPo battery pack",
      type: "cots",
      qty: 1,
      material: "lithium polymer pack",
      partNo: "4S 1500 mAh LiPo",
      description: "Strapped battery pack mounted beneath the center frame.",
      catalogNameSuggestions: ["4S 1500mAh LiPo battery", "FPV drone battery", "XT60 LiPo pack"],
      manufacturers: ["Tattu", "CNHL", "Gens Ace", "Spektrum"],
      specsToConfirm: ["cell count", "capacity", "C rating", "connector"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.8, 0.22, 0.46], position: [0, 0.66, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.92, 0.05, 0.08], position: [0, 0.8, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "flight-controller-stack",
      name: "Flight controller stack",
      type: "cots",
      qty: 1,
      material: "PCB stack",
      partNo: "F7 flight controller + 4-in-1 ESC",
      description: "Central control stack with IMU, power distribution, and motor ESC outputs.",
      catalogNameSuggestions: ["F7 flight controller stack", "4 in 1 ESC drone", "Betaflight flight controller"],
      manufacturers: ["Holybro", "Matek", "SpeedyBee", "iFlight"],
      specsToConfirm: ["mount pattern", "gyro", "ESC current rating", "firmware support"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.46, 0.06, 0.4], position: [0, 1.14, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.4, 0.06, 0.34], position: [0, 1.24, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "camera-gimbal",
      name: "Front camera and tilt mount",
      type: "cots",
      qty: 1,
      material: "camera module and printed mount",
      partNo: "HD micro camera",
      description: "Forward-facing camera payload for inspection video.",
      catalogNameSuggestions: ["HD micro FPV camera", "drone inspection camera", "micro camera tilt mount"],
      manufacturers: ["RunCam", "Caddx", "DJI", "Foxeer"],
      specsToConfirm: ["field of view", "voltage", "mount width", "video output"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.34, 0.22, 0.24], position: [0, 0.93, -0.43], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "cylinder", size: [0.12, 0.12, 0.08], position: [0, 0.94, -0.58], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "landing-gear",
      name: "Landing skid set",
      type: "custom",
      qty: 1,
      material: "printed nylon",
      partNo: "",
      description: "Low landing skids that protect the battery and camera during set-down.",
      catalogNameSuggestions: [],
      manufacturers: ["Cadybara", "local FDM print", "Xometry network"],
      specsToConfirm: ["ground clearance", "mount pattern", "impact material", "skid length"],
      geometry: {
        primitives: [
          { shape: "box", size: [1.25, 0.06, 0.08], position: [-0.52, 0.26, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.25, 0.06, 0.08], position: [0.52, 0.26, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.06, 0.38, 0.06], position: [-0.52, 0.45, -0.28], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.06, 0.38, 0.06], position: [0.52, 0.45, -0.28], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "gps-radio",
      name: "GPS, receiver, and antenna set",
      type: "cots",
      qty: 1,
      material: "radio electronics",
      partNo: "GPS + ELRS receiver",
      description: "Navigation and control radio hardware mounted above the frame.",
      catalogNameSuggestions: ["drone GPS module", "ELRS receiver", "FPV antenna"],
      manufacturers: ["u-blox", "Radiomaster", "TBS", "Matek"],
      specsToConfirm: ["frequency", "connector", "telemetry support", "antenna mounting"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.3, 0.06, 0.24], position: [0, 1.34, 0.28], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.035, 0.035, 0.38], position: [0.34, 1.36, 0.16], rotation: [0.3, 0, 0.2], colorRole: "cots" },
        ],
      },
    },
    {
      id: "wiring-fasteners",
      name: "Wiring and fastener kit",
      type: "cots",
      qty: 1,
      material: "silicone wire and steel hardware",
      partNo: "XT60 leads + M2/M3 hardware",
      description: "Power leads, signal wiring, standoffs, screws, and cable ties.",
      catalogNameSuggestions: ["XT60 silicone wire", "M3 drone standoff kit", "FPV drone hardware kit"],
      manufacturers: ["McMaster-Carr catalog", "RaceDayQuads", "GetFPV", "Digi-Key"],
      specsToConfirm: ["wire gauge", "connector type", "standoff height", "screw lengths"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.95, 0.035, 0.035], position: [-0.54, 0.98, -0.54], rotation: [0, 0.7854, 0], colorRole: "cots" },
          { shape: "box", size: [0.95, 0.035, 0.035], position: [0.54, 0.98, -0.54], rotation: [0, -0.7854, 0], colorRole: "cots" },
          { shape: "box", size: [0.95, 0.035, 0.035], position: [-0.54, 0.98, 0.54], rotation: [0, -0.7854, 0], colorRole: "cots" },
          { shape: "box", size: [0.95, 0.035, 0.035], position: [0.54, 0.98, 0.54], rotation: [0, 0.7854, 0], colorRole: "cots" },
        ],
      },
    },
  ],
};

export const fallbackProjects = [
  {
    id: "robot-arm",
    label: "Robot Arm",
    prompt: "Build a 6DOF robotic arm with a two-finger gripper",
    project: robotArmFallbackProject,
  },
  {
    id: "corexy-printer",
    label: "3D Printer",
    prompt: "Build a CoreXY 3D printer with a heated bed and enclosure",
    project: printerFallbackProject,
  },
  {
    id: "quadcopter",
    label: "Quadcopter",
    prompt: "Build an inspection quadcopter with prop guards and a camera payload",
    project: quadcopterFallbackProject,
  },
];

export function getFallbackProject(id = fallbackProjects[0].id) {
  return fallbackProjects.find((demo) => demo.id === id)?.project ?? fallbackProjects[0].project;
}

export function getFallbackPrompt(id = fallbackProjects[0].id) {
  return fallbackProjects.find((demo) => demo.id === id)?.prompt ?? fallbackProjects[0].prompt;
}

export const fallbackProject = getFallbackProject();
