export const fallbackProject = {
  projectName: "6DOF Robotic Arm",
  summary:
    "A desktop-scale 6-axis robotic arm with a rotating base, shoulder, elbow, wrist, and two-finger gripper.",
  statusLabel: "Fallback manifest",
  placeholders: [
    {
      title: "LLM hardware manifest",
      status: "Real when API key is configured",
      detail:
        "The backend asks the configured LLM provider for a structured manifest: project summary, BOM rows, catalog-name aliases, and simple 3D primitives.",
    },
    {
      title: "3D geometry",
      status: "Proxy CAD now",
      detail:
        "The viewer renders boxes, cylinders, and spheres from the manifest. Replace primitive arrays with Cadybara STEP/STL URLs when the CAD service is connected.",
    },
    {
      title: "Supplier search",
      status: "Generated links now",
      detail:
        "Supplier cards use catalog-name suggestions to build searches. A later version can call Octopart, Digi-Key, or distributor APIs for live pricing and stock.",
    },
    {
      title: "Pricing",
      status: "Placeholder",
      detail:
        "The schema has room for cost fields, but this demo intentionally avoids fake prices until a supplier API is wired in.",
    },
  ],
  parts: [
    {
      id: "base-plate",
      name: "Custom base plate",
      type: "custom",
      qty: 1,
      material: "6061 aluminum",
      partNo: "",
      description: "Mounting foundation with bolt pattern for the rotating base.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["plate thickness", "bolt pattern", "bearing pocket", "surface finish"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [1.35, 1.45, 0.18], position: [0, 0.06, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "base-bearing",
      name: "Slew bearing",
      type: "cots",
      qty: 1,
      material: "steel",
      partNo: "6815 thin-section bearing",
      description: "Large bearing that supports the vertical base rotation axis.",
      catalogNameSuggestions: ["6815 thin-section bearing", "slew bearing", "turntable bearing", "robot base bearing"],
      manufacturers: ["SKF", "NSK", "NTN", "Koyo", "Timken"],
      specsToConfirm: ["bore/OD/width", "sealed vs shielded", "load rating", "fit tolerance"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [1.05, 1.05, 0.16], position: [0, 0.25, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "j1-actuator",
      name: "J1 base actuator",
      type: "cots",
      qty: 1,
      material: "motor assembly",
      partNo: "NEMA 23 + 50:1 gearbox",
      description: "Primary yaw actuator for the arm base.",
      catalogNameSuggestions: [
        "NEMA 23 geared stepper motor",
        "servo motor with planetary gearbox",
        "robot joint actuator",
        "closed-loop stepper actuator",
      ],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA", "Oriental Motor"],
      specsToConfirm: ["stall torque", "speed", "voltage", "control protocol"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.62, 0.62, 0.62], position: [0, 0.62, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "shoulder-yoke",
      name: "Custom shoulder yoke",
      type: "custom",
      qty: 1,
      material: "6061 aluminum",
      partNo: "",
      description: "Forked bracket holding the shoulder joint bearings and actuator.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["bearing bore", "shaft clearance", "side plate thickness", "servo mount pattern"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.22, 1.02, 0.24], position: [-0.58, 1.22, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [0.22, 1.02, 0.24], position: [0.58, 1.22, 0], rotation: [0, 0, 0], colorRole: "custom" },
          { shape: "box", size: [1.34, 0.2, 0.3], position: [0, 0.82, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "j2-actuator",
      name: "J2 shoulder actuator",
      type: "cots",
      qty: 1,
      material: "servo assembly",
      partNo: "High-torque servo, 60 kg-cm",
      description: "Raises and lowers the upper arm link.",
      catalogNameSuggestions: ["high torque servo motor 60 kg-cm", "robot servo actuator", "digital servo motor", "smart servo motor"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA", "Oriental Motor"],
      specsToConfirm: ["stall torque", "horn spline", "voltage", "mounting tabs"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.42, 0.42, 0.82], position: [0, 1.34, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "upper-arm-link",
      name: "Custom upper arm link",
      type: "custom",
      qty: 1,
      material: "carbon fiber tube",
      partNo: "",
      description: "Lightweight structural member between shoulder and elbow.",
      catalogNameSuggestions: [],
      manufacturers: ["Rock West Composites", "DragonPlate", "local composites shop"],
      specsToConfirm: ["tube OD/ID", "fiber layup", "cut length", "insert bonding method"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.34, 1.95, 0.34], position: [0.46, 2.05, 0], rotation: [0, 0, -0.56], colorRole: "custom" },
        ],
      },
    },
    {
      id: "elbow-hub",
      name: "Custom elbow hub",
      type: "custom",
      qty: 1,
      material: "7075 aluminum",
      partNo: "",
      description: "Machined joint block connecting upper arm to forearm.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["bearing seat", "shaft bore", "clamp slots", "finish"],
      geometry: {
        primitives: [
          { shape: "sphere", size: [0.44, 0.44, 0.44], position: [0.93, 2.83, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "j3-actuator",
      name: "J3 elbow actuator",
      type: "cots",
      qty: 1,
      material: "servo assembly",
      partNo: "High-torque servo, 45 kg-cm",
      description: "Controls the elbow pitch axis.",
      catalogNameSuggestions: ["high torque servo motor 45 kg-cm", "robot elbow servo", "digital servo motor", "servo actuator"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA", "Oriental Motor"],
      specsToConfirm: ["stall torque", "speed", "voltage", "backlash"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.36, 0.36, 0.72], position: [0.93, 2.83, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "forearm-link",
      name: "Custom forearm link",
      type: "custom",
      qty: 1,
      material: "carbon fiber tube",
      partNo: "",
      description: "Second arm segment carrying wrist loads.",
      catalogNameSuggestions: [],
      manufacturers: ["Rock West Composites", "DragonPlate", "local composites shop"],
      specsToConfirm: ["tube OD/ID", "cut length", "end interface", "twist stiffness"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.28, 1.7, 0.28], position: [1.67, 2.56, 0], rotation: [0, 0, -1.07], colorRole: "custom" },
        ],
      },
    },
    {
      id: "wrist-housing",
      name: "Custom wrist housing",
      type: "custom",
      qty: 1,
      material: "nylon SLS",
      partNo: "",
      description: "Compact housing for the three wrist degrees of freedom.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local SLS bureau"],
      specsToConfirm: ["wall thickness", "servo clearance", "bearing seats", "wire routing"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.62, 0.48, 0.54], position: [2.16, 1.86, 0], rotation: [0, 0, 0], colorRole: "custom" },
        ],
      },
    },
    {
      id: "j4-actuator",
      name: "J4 wrist roll actuator",
      type: "cots",
      qty: 1,
      material: "micro servo",
      partNo: "Micro servo, metal gear",
      description: "Rotates the tool flange around the forearm axis.",
      catalogNameSuggestions: ["metal gear micro servo", "wrist roll servo", "micro servo actuator", "robot wrist servo"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA"],
      specsToConfirm: ["torque", "spline", "voltage", "case size"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.2, 0.2, 0.58], position: [2.18, 1.86, 0], rotation: [0, 0, 1.5708], colorRole: "cots" },
        ],
      },
    },
    {
      id: "j5-actuator",
      name: "J5 wrist pitch actuator",
      type: "cots",
      qty: 1,
      material: "micro servo",
      partNo: "Micro servo, metal gear",
      description: "Tilts the end effector up and down.",
      catalogNameSuggestions: ["metal gear micro servo", "wrist pitch servo", "micro servo actuator", "robot wrist servo"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA"],
      specsToConfirm: ["torque", "spline", "voltage", "case size"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.18, 0.18, 0.48], position: [2.48, 1.86, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "j6-actuator",
      name: "J6 wrist yaw actuator",
      type: "cots",
      qty: 1,
      material: "micro servo",
      partNo: "Micro servo, metal gear",
      description: "Final tool rotation axis.",
      catalogNameSuggestions: ["metal gear micro servo", "wrist yaw servo", "micro servo actuator", "robot wrist servo"],
      manufacturers: ["Hitec", "Savox", "Robotis Dynamixel", "goBILDA"],
      specsToConfirm: ["torque", "spline", "voltage", "case size"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.16, 0.16, 0.38], position: [2.75, 1.86, 0], rotation: [0, 0, 1.5708], colorRole: "cots" },
        ],
      },
    },
    {
      id: "tool-flange",
      name: "Custom tool flange",
      type: "custom",
      qty: 1,
      material: "6061 aluminum",
      partNo: "",
      description: "Universal wrist output plate for end effectors.",
      catalogNameSuggestions: [],
      manufacturers: ["Xometry network", "Protolabs", "Fictiv", "local CNC machine shop"],
      specsToConfirm: ["bolt circle", "pilot diameter", "tool pattern", "thickness"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.28, 0.28, 0.08], position: [2.98, 1.86, 0], rotation: [0, 0, 1.5708], colorRole: "custom" },
        ],
      },
    },
    {
      id: "gripper-kit",
      name: "Two-finger gripper kit",
      type: "cots",
      qty: 1,
      material: "gripper assembly",
      partNo: "Parallel gripper, 20 mm stroke",
      description: "Demo end effector for picking small objects.",
      catalogNameSuggestions: ["parallel robot gripper", "two finger gripper", "servo gripper kit", "robot end effector gripper"],
      manufacturers: ["RobotShop", "ServoCity", "Robotiq", "OnRobot", "Dobot"],
      specsToConfirm: ["stroke", "payload", "mount pattern", "servo or pneumatic"],
      geometry: {
        primitives: [
          { shape: "box", size: [0.18, 0.16, 0.72], position: [3.25, 2.04, 0.24], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.18, 0.16, 0.72], position: [3.25, 1.68, -0.24], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "box", size: [0.28, 0.38, 0.22], position: [3.1, 1.86, 0], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "joint-bearings",
      name: "Radial joint bearings",
      type: "cots",
      qty: 8,
      material: "steel",
      partNo: "608-2RS",
      description: "Support bearings for shoulder, elbow, and wrist shafts.",
      catalogNameSuggestions: ["608-2RS radial ball bearing", "8mm sealed ball bearing", "skate bearing 608-2RS", "robot joint bearing"],
      manufacturers: ["SKF", "NSK", "NTN", "Koyo", "Timken"],
      specsToConfirm: ["bore/OD/width", "seal type", "load rating", "quantity"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.48, 0.48, 0.06], position: [0, 1.34, 0.46], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.4, 0.4, 0.06], position: [0.93, 2.83, 0.4], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.24, 0.24, 0.05], position: [2.48, 1.86, 0.3], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "shaft-set",
      name: "Precision shaft set",
      type: "cots",
      qty: 6,
      material: "hardened steel",
      partNo: "8 mm hardened shaft",
      description: "Joint shafts and wrist axle stock.",
      catalogNameSuggestions: ["8mm hardened precision shaft", "8mm linear shaft", "ground steel shaft", "robot joint shaft"],
      manufacturers: ["MISUMI", "Thomson", "NB", "McMaster-Carr catalog"],
      specsToConfirm: ["diameter", "length", "material", "hardness"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.08, 0.08, 1.28], position: [0, 1.34, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.06, 0.06, 0.98], position: [0.93, 2.83, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.04, 0.04, 0.58], position: [2.48, 1.86, 0], rotation: [1.5708, 0, 0], colorRole: "cots" },
        ],
      },
    },
    {
      id: "fastener-kit",
      name: "Metric fastener kit",
      type: "cots",
      qty: 1,
      material: "alloy steel",
      partNo: "M3/M4 socket head assortment",
      description: "Assembly screws, washers, and locknuts.",
      catalogNameSuggestions: [
        "metric socket head cap screw assortment",
        "M3 M4 fastener kit",
        "metric machine screw kit",
        "robot hardware kit",
      ],
      manufacturers: ["McMaster-Carr catalog", "Bolt Depot", "Brighton-Best", "local hardware supplier"],
      specsToConfirm: ["thread size", "length mix", "head type", "washer/locknut needs"],
      geometry: {
        primitives: [
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [0.98, 0.21, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [-0.98, 0.21, 0], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [0, 0.21, 0.98], rotation: [0, 0, 0], colorRole: "cots" },
          { shape: "cylinder", size: [0.045, 0.045, 0.07], position: [0, 0.21, -0.98], rotation: [0, 0, 0], colorRole: "cots" },
        ],
      },
    },
  ],
};
